apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-springboot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp-springboot
  template:
    metadata:
      labels:
        app: myapp-springboot
    spec:
      containers:
        - name: springboot
          image: sanjeetkr/java_webapp:latest
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: app-springboot
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: myapp-springboot